### ISSUE TITLE
pcapy leaks memory

### ISSUE THREAD

**Issue by cnelson** [CoreSecurity/pcapy#12]
When running the following simple test application pcapy will continue to consume memory until it's killed.
## App

```
import pcapy

p = pcapy.open_live('any', 65535, False, 100)

while True:
    p.next()
```
## Memory Usage over a 30 minute period

![image](https://cloud.githubusercontent.com/assets/604163/13993221/b0b43240-f0dc-11e5-8828-b00905e7fec1.png)
## Environment

```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ find /usr/lib | grep libpcap
/usr/lib/x86_64-linux-gnu/libpcap.so.1.6.2
/usr/lib/x86_64-linux-gnu/libpcap.a
/usr/lib/x86_64-linux-gnu/libpcap.so
/usr/lib/x86_64-linux-gnu/libpcap.so.0.8

$ python3.4 --version
Python 3.4.2
```

**Comment by clayball** [comment]
FWIW, I can't reproduce this on Fedora 23 using Python 2.7.11 and pcapy 0.10.8-7.fc23.x86_64.

I copied the code above and saved it to check-mem.py. I get the following error

Traceback (most recent call last):
  File "./check-mem.py", line 6, in <module>
    p.next()
pcapy.PcapError

**Comment by cnelson** [comment]
@clayball The module's own tests fail on that platform with the same error.

I'd suggest anyone trying to reproduce this bug do it on the platform mentioned in the issue, or at least one where the module's own tests run successfully.


### Steps to reproduce on a new Fedora 23 AMI ( Fedora-Cloud-Base-23-20160609.x86_64 )
    [root@ip-172-31-10-201 tmp]# cd /tmp
    [root@ip-172-31-10-201 tmp]# yum install -y pcapy
    ...snipped...
    [root@ip-172-31-10-201 tmp]# cat /etc/os-release
    NAME=Fedora
    VERSION="23 (Cloud Edition)"
    ID=fedora
    VERSION_ID=23
    PRETTY_NAME="Fedora 23 (Cloud Edition)"
    ANSI_COLOR="0;34"
    CPE_NAME="cpe:/o:fedoraproject:fedora:23"
    HOME_URL="https://fedoraproject.org/"
    BUG_REPORT_URL="https://bugzilla.redhat.com/"
    REDHAT_BUGZILLA_PRODUCT="Fedora"
    REDHAT_BUGZILLA_PRODUCT_VERSION=23
    REDHAT_SUPPORT_PRODUCT="Fedora"
    REDHAT_SUPPORT_PRODUCT_VERSION=23
    PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
    VARIANT="Cloud Edition"
    VARIANT_ID=cloud

    [root@ip-172-31-10-201 tmp]# python --version
    Python 2.7.11

    [root@ip-172-31-10-201 tests]# yum list installed 2>&1| grep pcapy
    pcapy.x86_64                       0.10.8-7.fc23                @fedora

    [root@ip-172-31-10-201 tmp]# git clone https://github.com/CoreSecurity/pcapy
    ...snipped...
    [root@ip-172-31-10-201 tmp]# cd pcapy/ && git checkout 0.10.8 && cd tests && python pcapytests.py
    HEAD is now at 2984bf5... Added README with markdown syntax.
    testEOFValue (__main__.TestPcapy)
    #1:when next() creates a pkthdr it make one extra reference ... ERROR
    testPacketHeaderRefCount (__main__.TestPcapy)
    #1:when next() creates a pkthdr it make one extra reference ... ok

    ======================================================================
    ERROR: testEOFValue (__main__.TestPcapy)
    #1:when next() creates a pkthdr it make one extra reference
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "pcapytests.py", line 32, in testEOFValue
        s = r.next()
    PcapError

    ----------------------------------------------------------------------
    Ran 2 tests in 0.001s

    FAILED (errors=1)

**Comment by martinuy** [comment]
This looks like a timing issue between the packets producer (the network, using a wide filter) and the consumer (_pcap.next()_ called from Python). Memory consumption grows because packets get buffered faster than removed from the buffer.

In order to verify this hypothesis, you can add a time.sleep in the loop and we must see a higher inclined line (given the same number of network packets captured).

My suggestions are the following:

- Use a narrow filter
- Use a dispatch callback instead of manually calling next (better performance)
- Set the Pcap buffer size in order to drop packets (still not possible in Pcapy, see #17)

**Comment by guyharris** [comment]
> Memory consumption grows because packets get buffered faster than removed from the buffer.

Presumably they're being buffered by pcapy or Python; libpcap doesn't buffer an arbitrary number of packets.  (This is Linux, so it's probably using TPACKET with a fixed-size buffer shared between the kernel and userland, with packets simply being discarded by the kernel if they're arriving faster than userland can consume them; even if it's an ancient kernel without TPACKET, so that libpcap is doing `recvfrom()` calls, it does them into a buffer that's allocated at open time - it doesn't allocate a new buffer for each packet.)

**Comment by jab1982** [comment]
Is there anyone investigating this issue? The problem persists. Narrowing down the search did not help. After filter, I have 122pkt/s. It happens on Mac Sierra and Centos 6.5 with Python 3.6.1. This basic code is enough to try: http://snipplr.com/view/3579/live-packet-capture-in-python-with-pcapy/ Memory gets to 2GB in 8 hours.

**Comment by Avishay116** [comment]
Use pcapy 0.11.5.
The memory leak problem is solved in this version.
Note: this version is not yet on pypi, so download it from "releases" and install it manually. 

Good luck
